### ISSUE TITLE
[Feature] 应该有个默认配置文件的json环境变量

### ISSUE THREAD

**Issue by Mxucc** [ChatGPTNextWeb/ChatGPT-Next-Web#3695]
> 为了提高交流效率，我们设立了官方 QQ 群和 QQ 频道，如果你在使用或者搭建过程中遇到了任何问题，请先第一时间加群或者频道咨询解决，除非是可以稳定复现的 Bug 或者较为有创意的功能建议，否则请不要随意往 Issue 区发送低质无意义帖子。

> [点击加入官方群聊](https://github.com/Yidadaa/ChatGPT-Next-Web/discussions/1724)

**这个功能与现有的问题有关吗？**
环境变量问题，默认模式配置问题

**你想要什么功能或者有什么建议？**
在环境变量中写入配置文件的url或者文件内容，文件由调好的本地数据导出，作为程序启动后读取作为默认的本地配置

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。
![image](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/128977511/9936019d-a851-42de-88ba-e60f3d07815b)
在环境变量调用这个保存好的配置作为初始配置

**其他信息**
可以说说你的其他考虑。

**Comment by Mxucc** [comment]
同时也能满足这个 https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3676

**Comment by MapleMoonSky** [comment]
可以自己创建一个`.env`保存环境变量
```bash
docker-compose up --env-file .env
```

也可以在docker-compose.yml文件中使用env_file选项来指定.env文件的路径。例如：
```yml
version: '3.7'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    env_file:
      - .env
```
