### ISSUE TITLE
[Bug] Nginx 無法反代本地的GPT4模型

### ISSUE THREAD

**Issue by WillWang2122** [ChatGPTNextWeb/ChatGPT-Next-Web#4645]
### Bug Description

在我的伺服器上為了解決CORS的問題，所以我做了如下的設定:
反代 app.mydomain.com/gui 到nextweb (前端GUI)， nginx 設定如下：
location ^~ /gui {
    proxy_pass http://172.17.0.4:3000/; 
    proxy_set_header Host $host; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
    add_header X-Cache $upstream_cache_status; 
    add_header Strict-Transport-Security "max-age=31536000"; 
    add_header Cache-Control no-cache; 
}

在app.mydomain.com 的root 是反代到我的後端模型的endpoint.
location ^~ / {
    proxy_pass http://172.17.0.9:7077; 
    proxy_set_header Host $host; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
    add_header X-Cache $upstream_cache_status; 
    add_header Strict-Transport-Security "max-age=31536000"; 
    add_header Cache-Control no-cache; 
}

我發現在第一個請求之後的下一個請求，請求 app.mydomain.com 而不是 app.mydomain.com/gui，導致 404 錯誤。我該如何確保下一個請求仍然發送到 app.mydomain.com/gui，並且 nginx 將其代理到正確的內部 IP 和端口？
在部署的時候有寫到base url = app.mydomain.com/gui

### Steps to Reproduce

我是用docker 部署nextweb的: docker compose file 如下：
```
networks:
    1panel-network:
        external: true
services:
    chatgpt-next-web:
        container_name: ${CONTAINER_NAME}
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        environment:
            - OPENAI_API_KEY=${API_KEY}
            - CODE=${SECRET_KEY}
            - PROXY_URL=${PROXY}
            - BASE_URL=${API_BASE_URL}
        image: yidadaa/chatgpt-next-web:v2.12.2
        labels:
            createdBy: Apps
        networks:
            - 1panel-network
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:3000
        restart: always
```
然後就是設定nginx
設定 Nginx 反向代理至前端 GUI： 在的 Nginx 設定檔中，為 app.mydomain.com/gui 設定一個 location 區塊，並將其反向代理至前端 GUI（位於 http://172.17.0.4:3000/）。以下是相關的 Nginx 設定：

location ^~ /gui {
    proxy_pass http://172.17.0.4:3000/; 
    proxy_set_header Host $host; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
    add_header X-Cache $upstream_cache_status; 
    add_header Strict-Transport-Security "max-age=31536000"; 
    add_header Cache-Control no-cache; 
}

設定 Nginx 反向代理至後端： 在 Nginx 設定檔中，為 app.mydomain.com 的根目錄設定一個 location 區塊，並將其反向代理至後端（位於 http://172.17.0.9:7077）。以下是相關的 Nginx 設定：

location ^~ / {
    proxy_pass http://172.17.0.9:7077; 
    proxy_set_header Host $host; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
    add_header X-Cache $upstream_cache_status; 
    add_header Strict-Transport-Security "max-age=31536000"; 
    add_header Cache-Control no-cache; 
}

### Expected Behavior

Nextweb 正常運作

### Screenshots

![Screenshot 2024-05-09 155434](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/168748301/32dd395b-6b7e-4c1d-b7a6-3a061db075e2)
![Screenshot 2024-05-09 155631](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/168748301/1c3f410a-5c0c-4019-a1c6-11927f0227a0)

### Deployment Method

- [ ] Docker
- [ ] Vercel
- [X] Server

### Desktop OS

Windows11

### Desktop Browser

Chrome

### Desktop Browser Version

125.0.6422.41
