### ISSUE TITLE
Build a personal assistant based on Tongyi Qwen(通义千问) 2.5 using Higress + NextChat.

### ISSUE THREAD

**Issue by johnlanni** [ChatGPTNextWeb/ChatGPT-Next-Web#4681]
> Higress GitHub page: https://github.com/alibaba/higress

## Step 1: Create a file named `docker-compose.yml` and fill in the following content:

> Note:
> 1. Replace `YOUR_DASHSCOPE_API_KEY` with your own [Dashscope API Key](https://help.aliyun.com/zh/dashscope/opening-service?spm=a2c4g.11186623.0.0.72c2369dLprd45);
> 2. Replace `/path-to-local-config-folder` with a local directory path that can be used to save configuration files.

```yaml
version: '3.9'

networks:
  higress-net:
    external: false

services:
  higress:
    image: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/all-in-one:1.3.6
    environment:
      - CONFIG_TEMPLATE=ai-proxy
      - DEFAULT_AI_SERVICE=qwen
      - DASHSCOPE_API_KEY=YOUR_DASHSCOPE_API_KEY
    networks:
      - higress-net
    ports:
      - "8080:8080/tcp"
      - "8001:8001/tcp"
    volumes:
      - /path-to-local-config-folder:/data
    restart: always
  nextchat:
    image: yidadaa/chatgpt-next-web
    environment:
      - OPENAI_API_KEY=unused
      - BASE_URL=http://higress:8080
    networks:
      - higress-net
    ports:
      - "3000:3000/tcp"
    restart: always
    
```

## Step 2：Run the following command in the command line to start the docker compose project:

```bash 
docker compose –p higress-ai up –d 
```

## Step 3：Access http://localhost:3000/ in your browser to open NextChat page;

![image](https://github.com/alibaba/higress/assets/6763318/9f94c99d-b8c3-462b-91a7-a730d80c99b1)

## Step 4：Click on the model settings button at the far right of the conversation input box toolbar, switch the model to `gpt-4-turbo`, and close the window.

Because Higrss's AI Proxy plugin (you can access http://localhost:8001 to view plugin configuration) is configured with gpt-4-turbo mapped to qwen-max, so actually here provides qwen-max as model service.

![image](https://github.com/alibaba/higress/assets/6763318/6b516d9f-b7ab-432f-bb64-6d6aade60467)

Done! Now you can have a conversation with AI.

![image](https://github.com/alibaba/higress/assets/6763318/accf9fd7-8497-41d0-9feb-474d7d725e1f)

Follow the above instructions for configuration, by default, you will have conversations with Tongyi Qwen (通义千问). If you want to switch to OpenAI ChatGPT, just modify `DEFAULT_AI_SERVICE=qwen` in the file as `DEFAULT_AI_SERVICE=openai`, add OpenAI's API key configuration, and then restart docker compose project.

```yaml 
# Configuration above omitted.
  higress:
    image: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/all-in-one:1.3.6
    environment:
      - CONFIG_TEMPLATE=ai-proxy
      - DEFAULT_AI_SERVICE=openai
      - OPENAI_API_KEY=YOUR_OPENAI_API_KEY
# Configuration below omitted.
```
```bash
docker compose -p higress-ai down
docker compose -p higress-ai up -d
```
