### ISSUE TITLE
[Bug] 2.12.3 使用PROXY_URL部署后无法访问

### ISSUE THREAD

**Issue by DoctorReid** [ChatGPTNextWeb/ChatGPT-Next-Web#4795]
### Bug Description

同样的docker-compose配置，使用 2.12.2版本可以正常运行，使用2.12.3就不行了。

使用2.12.3去掉PROXY_URL也能正常运行。

### Steps to Reproduce

使用如下的 compose.yaml 部署，改版本号即可复现

```yaml
services:
  clash:
    image: dreamacro/clash-premium
    volumes:
      - ./WgetCloud.yaml:/root/.config/clash/config.yaml
    restart: unless-stopped
    networks:
      net1:
        ipv4_address: 172.28.0.2
    expose:
      - "9990"
    ports:
      - 9990:9990
  chatgpt-next-web:
    image: yidadaa/chatgpt-next-web:v2.12.2
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CODE: ${CHATGPT_NEXT_WEB_CODE}
      PROXY_URL: http://172.28.0.2:9990
    expose:
      - "3000"
    ports:
      - 9800:3000
    networks:
      net1:
        ipv4_address: 172.28.0.3

networks:
  net1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
```

### Expected Behavior

2.12.3可以使用PROXY_URL运行

### Deployment Method

- [X] Docker
- [ ] Vercel
- [ ] Server
