### ISSUE TITLE
[Bug] Self-Deploied WEBDAV service can't be used to backup

### ISSUE THREAD

**Issue by Dandi007** [ChatGPTNextWeb/ChatGPT-Next-Web#5066]
### 📦 Deployment Method

Docker

### 📌 Version

v2.12.4

### 💻 Operating System

Ubuntu

### 📌 System Version

22.04

### 🌐 Browser

Chrome

### 📌 Browser Version

Google Chrome 126.0.6478.126 

### 🐛 Bug Description

I have deploied my webdav service, and can access it with curl

`➜  ~ curl -u USERNAME:PASSWD http://MY_HOSTNAME:3971/`

got html output:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
 <head>
  <title>Index of /</title>
 </head>
 <body>
<h1>Index of /</h1>
<ul><li><a href="a.txt"> a.txt</a></li>
<li><a href="testfile.txt"> testfile.txt</a></li>
</ul>
</body></html>
```

but In my nextchat's config, I click "检查可用性” (check available）
it sends http req

https://MY_CHAT_HOST/api/webdav/chatgpt-next-web?endpoint=http://MY_ADV_HOST:3971

got 400 bad request

when I click sync
it sends http req
https://MY_CHAT_HOST/api/webdav/chatgpt-next-web/backup.json?endpoint=http://MY_ADV_HOST:3971
got resp
404

I have already insert my endpoint to white list using docker-compose

```
  chatgpt:
    image: yidadaa/chatgpt-next-web:using
    container_name: chatgpt
    environment:
      - WHITE_WEBDEV_ENDPOINTS=http://www.qinglinzhang.top:3971
    restart: always
```
