### ISSUE TITLE
[Bug] 无法使用豆包大模型

### ISSUE THREAD

**Issue by TCOTC** [ChatGPTNextWeb/ChatGPT-Next-Web#5069]
### 📦 部署方式

官方安装包

### 📌 软件版本

v2.13.1

### 💻 系统环境

Windows

### 📌 系统版本

22H2

### 🌐 浏览器

Chrome

### 📌 浏览器版本

126.0.6478.128

### 🐛 问题描述

豆包的接口地址是 https://ark.cn-beijing.volces.com/api/v3 ，但填写了没用，始终请求 https://ark.cn-beijing.volces.com/api/v1/chat/completions ，没有 v3

### 📷 复现步骤

桌面端不知道哪里有开发者工具，拿网页演示一下：

https://github.com/user-attachments/assets/edae0d06-3daa-4261-828b-7dfd42468d85

### 🚦 期望结果

正常请求正常使用

**Comment by lloydzhou** [comment]
使用自定义接口的时候，接口地址填写：
https://ark.cn-beijing.volces.com

**Comment by TCOTC** [comment]
填写 https://ark.cn-beijing.volces.com/ 之后请求的地址还是会加上 v1/chat/completions

![image](https://github.com/user-attachments/assets/c43a4d3d-0fa2-41e2-9a27-4ecbca8ad4f8)

> 豆包的使用需要配合CUSTOM_MODELS一起(配置部署名称)使用

这是指什么？不是接入点名称吗？

**Comment by lloydzhou** [comment]
README中有相关说明

![image](https://github.com/user-attachments/assets/58050929-1a29-4367-a745-ad5b762f1389)

**Comment by TCOTC** [comment]
我这里还是不成功，不知道我哪里还有问题

![image](https://github.com/user-attachments/assets/1069e34b-1bcf-47d1-a361-c6692589ba4e)

![image](https://github.com/user-attachments/assets/9d56188e-a7b2-48f0-ad29-d4577f4fe406)

**Comment by ylacmilan** [comment]
跟我一样 不知道咋回事

**Comment by Crazykev** [comment]
![image](https://github.com/user-attachments/assets/9bc30104-a27b-4e5e-9cc3-17ea6b957466)
对话框跟我情况一样，像是逻辑有bug，抓了下包，刚开始会通过OPTIONS去访问https://ark.cn-beijing.volces.com/api/v3/chat/completions，但是没有带任何auth key，报了401.
而且这个行为也很奇怪，本地试了下及时带了key，也会报404。交互协议对不上

**Comment by lloydzhou** [comment]
@Crazykev OPTIONS请求是HTTP协议里面在跨域的时候的标准做法。先通过OPTIONS接口检查是否支持跨域。检查通过之后再发送POST请求。

**Comment by woxiangshuo** [comment]
{
  "error": true,
  "message": "you are not allowed to use Doubao-vision-pro-32k model"
}
这咋回事啊？

**Comment by github-pigsy** [comment]
我也遇到相同的问题，但是排查了配置信息，也没发现哪里出错
![].(https://raw.githubusercontent.com/github-pigsy/picgoprivate/main/data/image/20250110201824.png)

`{
  "error": true,
  "message": "NetworkError when attempting to fetch resource."
}
`

**Comment by yuanyehome** [comment]
any updates on this?

**Comment by github-pigsy** [comment]
> any updates on this?
Thank you reply
Already solve it, I was just modify docker config.
```
services:
  chatgpt-next-web:
    image: yidadaa/chatgpt-next-web:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - CUSTOM_MODELS=-all,**+Doubao-pro-128k@bytedance=ep-20250109085906-x9ghk**
      - BYTEDANCE_API_KEY=xxxxx
    
```
