### ISSUE TITLE
[Bug] Cannot upload or generate images

### ISSUE THREAD

**Issue by sysoppl** [ChatGPTNextWeb/ChatGPT-Next-Web#5224]
### 📦 Deployment Method

Docker

### 📌 Version

2.14.1

### 💻 Operating System

Ubuntu

### 📌 System Version

24.04 LTS

### 🌐 Browser

Chrome

### 📌 Browser Version

127.0.6533.89

### 🐛 Bug Description

When I'm trying to upload photo using gpt4o or generate one using dalle3 i got this error:
```
{
    "error": true,
    "msg": "you are not allowed to request upload"
}
```

I cleared any app data without any success

### 📷 Recurrence Steps

1. Start docker with this config:
```
version: "3.9"
services:
  chatgpt-next-web-proxy:
    container_name: chatgpt-next-web-proxy
    image: yidadaa/chatgpt-next-web
    ports:
      - 5173:3000
    environment:
      - CODE=1234
      - CUSTOM_MODELS=-all,+gpt-4o,-gpt-4o@azure=gpt4o(Azure),+gpt-4o-mini,-gpt-4o-mini@azure=gpt-4o-mini(Azure),+dall-e-3
      - OPENAI_API_KEY=xxxx
      - HIDE_USER_API_KEY=1
```

2. Open URL
3. Select model
4. Upload photo or send prompt to generate one
5. Errors in console
![image](https://github.com/user-attachments/assets/dcb2474b-0e4b-4e9f-81b1-1f9b824d41fb)

### 🚦 Expected Behavior

Be able to upload images to cache

### 📝 Additional Information

I'm using cloudflare proxy (DNS), VPN and Nginx Proxy Manager to expose site to the world.
Uploading was working few weeks ago.
