### ISSUE TITLE
[Bug] 从 v2.15.3 开始 Azure 模型无法生成标题

### ISSUE THREAD

**Issue by jia-niang** [ChatGPTNextWeb/ChatGPT-Next-Web#5575]
### 📦 部署方式

Docker

### 📌 软件版本

v2.15.3

### 💻 系统环境

Ubuntu

### 📌 系统版本

22.04.4 LTS

### 🌐 浏览器

Chrome

### 📌 浏览器版本

129.0.6668.71 (ARM)

### 🐛 问题描述

v2.15.3 版本开始，如果不用 OpenAI 的模型，那么无法正确生成对话的标题，前一个版本是正常的。

给出我的 Docker 配置：

旧版本（v2.15.2）：
```yaml
  gpt:
    image: yidadaa/chatgpt-next-web:v2.15.2
    environment:
      - AZURE_URL=
      - AZURE_API_KEY=
      - AZURE_API_VERSION=2024-02-01
      - CUSTOM_MODELS=-all,+gpt-4o@Azure,+gpt-4o-mini@Azure
```
此时可以自动调用 `gpt-4o-mini` 模型来生成标题，结果如下图：
![image](https://github.com/user-attachments/assets/62019158-5020-4e28-9526-dde62d4ce0af)

-----
新版本，把版本号改成 `v2.15.3` 重新启动 Docker，此时就无法正确为问答生成标题了。
如下图：
![image](https://github.com/user-attachments/assets/073527a2-54e6-44d9-8873-94dd0265a7cc)

查看后台日志输出，会发现生成标题又使用了 OpenAI 默认的模型。
