### ISSUE TITLE
[Bug] 配合litellm，无法使用DuckDuckGoLite插件

### ISSUE THREAD

**Issue by liudhzhyym** [ChatGPTNextWeb/ChatGPT-Next-Web#5653]
### 📦 部署方式

Docker

### 📌 软件版本

v2.15.4

### 💻 系统环境

Ubuntu

### 📌 系统版本

18.04

### 🌐 浏览器

Chrome

### 📌 浏览器版本

128.0.6613.138

### 🐛 问题描述

由于需要使用多个模型（openai、aws bedrock），我们加了litellm作为前置代理，litellm配置如下：
```yaml
model_list:
  - model_name: "claude-3.5-sonnet"
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
      aws_access_key_id: xxxx
      aws_secret_access_key: xxxxxxxxxxxxxxx
      aws_region_name: us-east-1
  - model_name: "openai/*"
    litellm_params:
      model: "openai/*"
      api_base: https://api.openai.com/v1 # e.g. http://0.0.0.0:3000/v1
      api_key: sk-proj-xxxxxxxxxxxxxxxxxx

litellm_settings:
    modify_params: true
    drop_params: true
```

启动命令为：`litellm --port 3005 --config config.yaml`
docker启动命令为：`docker run -d -e BASE_URL=http://127.0.0.1:3005 -e CUSTOM_MODELS=claude-3.5-sonnet -e DEFAULT_MODEL=gpt-4o --net=host -e PORT=3000 yidadaa/chatgpt-next-web`

模型正常对话没有问题，但是在使用插件时，提示失败，调用接口出现500错误，后端docker日志如下：
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/575d4906-f983-43dd-b3ba-cda1fbbf644b">

```
[proxy Route] params  { provider: 'proxy', path: [ 'lite' ] }
[Proxy Route] params  { provider: 'proxy', path: [ 'lite' ] }
 ⨯ Error: fetch failed
    at context.fetch (/app/node_modules/next/dist/server/web/sandbox/context.js:272:38)
    at r (/app/.next/server/edge-chunks/297.js:5589:76)
    at doOriginalFetch (/app/.next/server/edge-chunks/297.js:10384:24)
    at /app/.next/server/edge-chunks/297.js:10509:20
    at /app/.next/server/edge-chunks/297.js:10759:36
    at NoopContextManager.with (/app/.next/server/edge-chunks/297.js:732:30)
    at ContextAPI.with (/app/.next/server/edge-chunks/297.js:402:58)
    at NoopTracer.startActiveSpan (/app/.next/server/edge-chunks/297.js:1325:34)
    at ProxyTracer.startActiveSpan (/app/.next/server/edge-chunks/297.js:1365:36)
    at /app/.next/server/edge-chunks/297.js:10748:103 {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (eval at requireWithFakeGlobalScope (/app/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:9145:28)
      at eval (eval at requireWithFakeGlobalScope (/app/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:9101:50)
      at Immediate.eval [as _onImmediate] (eval at requireWithFakeGlobalScope (/app/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:9133:13)
      at process.processImmediate (node:internal/timers:476:21)
      at process.callbackTrampoline (node:internal/async_hooks:128:17) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
```

尝试去掉litellm proxy，`docker run -d -e OPENAI_API_KEY=sk-proj-xxxx --net=host -e PROXY_URL=http://172.31.7.209:23530 -e PORT=3000 yidadaa/chatgpt-next-web` ，可以正常使用插件
