### ISSUE TITLE
[Bug] DeekSeek related environment not work

### ISSUE THREAD

**Issue by hustlibraco** [ChatGPTNextWeb/ChatGPT-Next-Web#6048]
### 📦 Deployment Method

Docker

### 📌 Version

v2.15.8

### 💻 Operating System

Other Linux

### 📌 System Version

Alpine Linux 3.20

### 🌐 Browser

Chrome

### 📌 Browser Version

131.0.6778.205

### 🐛 Bug Description

I deployed nextweb via Docker Compose. I want the service to work by default through the deepseek model without relying on any configuration in the front-end page. This is my original compose file.
```
version: "3"
services:
  chatgpt-web:
    image: yidadaa/chatgpt-next-web:latest
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - CODE=xxxxxx
      - CUSTOM_MODELS=-all,+deepseek-chat@DeepSeek
      - DEFAULT_MODEL=deepseek-chat
      - DEEPSEEK_URL=https://api.deepseek.com
      - DEEPSEEK_API_KEY=sk-xxxx
```
But it didn't work. seeing the logs, nextweb still request the apis of openai instead of deepseek.
Then I update my compose file like this, adding **OPENAI_API_KEY** and **BASE_URL** configs, pretend to request custom openai url with specified model *deepseek-chat*, and it works well.
```
version: "3"
services:
  chatgpt-web:
    image: yidadaa/chatgpt-next-web:latest
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - OPENAI_API_KEY=sk-xxxx
      - BASE_URL=https://api.deepseek.com
      - CODE=xxxxxx
      - CUSTOM_MODELS=-all,+deepseek-chat@DeepSeek
      - DEFAULT_MODEL=deepseek-chat
      - DEEPSEEK_URL=https://api.deepseek.com
      - DEEPSEEK_API_KEY=sk-xxxx
```

I think there is something wrong with **DEEPSEEK_URL** and **DEEPSEEK_API_KEY** config items, or my misconfig, plz let me know the truth, thank you!
